name: ml_project
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - joblib
  - pyarrow
  # plotting
  - matplotlib
  - seaborn
  # gradient boosting
  - xgboost
  - lightgbm
  # pip packages
  - pip:
      - torch
      - transformers
      - sentence-transformers
      - langdetect
      - vadersentiment
